spring:
  imageProxy: https://pic1.xuehuaimg.com/proxy/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.79.216:3306/sms?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: sms
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080